version: "3.9"
services:
  backend_blue:
    build: .
    container_name: backend_blue
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - APP_COLOR=blue
    # ports:
    #   - "8000:8000"
    depends_on:
      - db
    # This is for local development with hot reload, no need in production
    # volumes:
    #   - ./app:/app/app
    #   - ./alembic:/app/alembic

    command: >
      sh -c "alembic -c alembic.ini upgrade head &&
             gunicorn -k uvicorn.workers.UvicornWorker app.main:app
             --bind 0.0.0.0:8000 --workers 3 --timeout 60"

  backend_green:
    build: .
    container_name: backend_green
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - APP_COLOR=green
    depends_on:
      - db
    command: >
      sh -c "alembic -c alembic.ini upgrade head &&
             gunicorn -k uvicorn.workers.UvicornWorker app.main:app
             --bind 0.0.0.0:8000 --workers 3 --timeout 60"

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend_blue
      - backend_green

  db:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-backend_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
